name: Testing

on:
  pull_request:
    branches:
    - main

jobs:

  swiftlang_checks:
    name: Swiftlang Checks
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@0.0.15
    with:
      license_header_check_project_name: "feather-openapi"

  swiftlang_tests:
    name: Swiftlang Tests
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@0.0.15
    with:
      enable_windows_checks : false
      linux_build_command: "swift test --parallel --enable-code-coverage"
      linux_swift_versions: '["6.1", "6.2", "6.3", "6.4"]'
